-- User 1: For RAD domain (PRD and NONPRD DBA roles)
CREATE USER rad_admin
  PASSWORD = 'RadAdmin#2024!'
  DEFAULT_ROLE = RAD_NONPRD_DBA
  DEFAULT_WAREHOUSE = RAD_DEV_DATA_LOADER
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE RAD_NONPRD_DBA TO USER rad_admin;
GRANT ROLE RAD_PRD_DBA TO USER rad_admin;

-- User 2: For ESG domain (PRD and NONPRD DBA roles)
CREATE USER esg_admin
  PASSWORD = 'EsgAdmin#2024!'
  DEFAULT_ROLE = ESG_NONPRD_DBA
  DEFAULT_WAREHOUSE = ESG_DEV_DATA_LOADER
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE ESG_NONPRD_DBA TO USER esg_admin;
GRANT ROLE ESG_PRD_DBA TO USER esg_admin;

-- User 3: For MIM domain (PRD and NONPRD DBA roles)
CREATE USER mim_admin
  PASSWORD = 'MimAdmin#2024!'
  DEFAULT_ROLE = MIM_NONPRD_DBA
  DEFAULT_WAREHOUSE = MIM_DEV_DATA_LOADER
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE MIM_NONPRD_DBA TO USER mim_admin;
GRANT ROLE MIM_PRD_DBA TO USER mim_admin;

-- User 4: For RAD domain (PRD and NONPRD DBA roles)
CREATE USER rad_dba
  PASSWORD = 'RadDba#2024!'
  DEFAULT_ROLE = RAD_PRD_DBA
  DEFAULT_WAREHOUSE = RAD_PRD_ETL
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE RAD_NONPRD_DBA TO USER rad_dba;
GRANT ROLE RAD_PRD_DBA TO USER rad_dba;
