-- Grant privileges for RAD domain

-- Grant to RAD_NONPRD_DBA (non-prod)
GRANT USAGE ON WAREHOUSE RAD_DEV_DATA_LOADER TO ROLE RAD_NONPRD_DBA;
GRANT OPERATE ON WAREHOUSE RAD_DEV_DATA_LOADER TO ROLE RAD_NONPRD_DBA;

GRANT USAGE ON WAREHOUSE RAD_TST_DATA_LOADER TO ROLE RAD_NONPRD_DBA;
GRANT OPERATE ON WAREHOUSE RAD_TST_DATA_LOADER TO ROLE RAD_NONPRD_DBA;

GRANT USAGE ON WAREHOUSE RAD_DEV_ETL TO ROLE RAD_NONPRD_DBA;
GRANT OPERATE ON WAREHOUSE RAD_DEV_ETL TO ROLE RAD_NONPRD_DBA;

GRANT USAGE ON WAREHOUSE RAD_TST_ETL TO ROLE RAD_NONPRD_DBA;
GRANT OPERATE ON WAREHOUSE RAD_TST_ETL TO ROLE RAD_NONPRD_DBA;

GRANT USAGE ON WAREHOUSE RAD_DEV_TABLEAU TO ROLE RAD_NONPRD_DBA;
GRANT OPERATE ON WAREHOUSE RAD_DEV_TABLEAU TO ROLE RAD_NONPRD_DBA;

GRANT USAGE ON WAREHOUSE RAD_TST_TABLEAU TO ROLE RAD_NONPRD_DBA;
GRANT OPERATE ON WAREHOUSE RAD_TST_TABLEAU TO ROLE RAD_NONPRD_DBA;

-- Grant to RAD_PRD_DBA (prod)
GRANT USAGE ON WAREHOUSE RAD_PRD_DATA_LOADER TO ROLE RAD_PRD_DBA;
GRANT OPERATE ON WAREHOUSE RAD_PRD_DATA_LOADER TO ROLE RAD_PRD_DBA;

GRANT USAGE ON WAREHOUSE RAD_PRD_ETL TO ROLE RAD_PRD_DBA;
GRANT OPERATE ON WAREHOUSE RAD_PRD_ETL TO ROLE RAD_PRD_DBA;

GRANT USAGE ON WAREHOUSE RAD_PRD_TABLEAU TO ROLE RAD_PRD_DBA;
GRANT OPERATE ON WAREHOUSE RAD_PRD_TABLEAU TO ROLE RAD_PRD_DBA;

-- Grant to RAD_DEV_ETL
GRANT USAGE ON WAREHOUSE RAD_DEV_DATA_LOADER TO ROLE RAD_DEV_ETL;
GRANT OPERATE ON WAREHOUSE RAD_DEV_DATA_LOADER TO ROLE RAD_DEV_ETL;

GRANT USAGE ON WAREHOUSE RAD_DEV_ETL TO ROLE RAD_DEV_ETL;
GRANT OPERATE ON WAREHOUSE RAD_DEV_ETL TO ROLE RAD_DEV_ETL;

GRANT USAGE ON WAREHOUSE RAD_DEV_TABLEAU TO ROLE RAD_DEV_ETL;
GRANT OPERATE ON WAREHOUSE RAD_DEV_TABLEAU TO ROLE RAD_DEV_ETL;

-- Grant to RAD_TST_ETL
GRANT USAGE ON WAREHOUSE RAD_TST_DATA_LOADER TO ROLE RAD_TST_ETL;
GRANT OPERATE ON WAREHOUSE RAD_TST_DATA_LOADER TO ROLE RAD_TST_ETL;

GRANT USAGE ON WAREHOUSE RAD_TST_ETL TO ROLE RAD_TST_ETL;
GRANT OPERATE ON WAREHOUSE RAD_TST_ETL TO ROLE RAD_TST_ETL;

GRANT USAGE ON WAREHOUSE RAD_TST_TABLEAU TO ROLE RAD_TST_ETL;
GRANT OPERATE ON WAREHOUSE RAD_TST_TABLEAU TO ROLE RAD_TST_ETL;

-- Grant to RAD_PRD_ETL
GRANT USAGE ON WAREHOUSE RAD_PRD_DATA_LOADER TO ROLE RAD_PRD_ETL;
GRANT OPERATE ON WAREHOUSE RAD_PRD_DATA_LOADER TO ROLE RAD_PRD_ETL;

GRANT USAGE ON WAREHOUSE RAD_PRD_ETL TO ROLE RAD_PRD_ETL;
GRANT OPERATE ON WAREHOUSE RAD_PRD_ETL TO ROLE RAD_PRD_ETL;

GRANT USAGE ON WAREHOUSE RAD_PRD_TABLEAU TO ROLE RAD_PRD_ETL;
GRANT OPERATE ON WAREHOUSE RAD_PRD_TABLEAU TO ROLE RAD_PRD_ETL;

-- Repeat for ESG and MIM domains

-- Grant privileges for ESG domain

GRANT USAGE ON WAREHOUSE ESG_DEV_DATA_LOADER TO ROLE ESG_NONPRD_DBA;
GRANT OPERATE ON WAREHOUSE ESG_DEV_DATA_LOADER TO ROLE ESG_NONPRD_DBA;

GRANT USAGE ON WAREHOUSE ESG_PRD_DATA_LOADER TO ROLE ESG_PRD_DBA;
GRANT OPERATE ON WAREHOUSE ESG_PRD_DATA_LOADER TO ROLE ESG_PRD_DBA;

-- Follow similar pattern for other roles and warehouses

-- Grant privileges for MIM domain

GRANT USAGE ON WAREHOUSE MIM_DEV_DATA_LOADER TO ROLE MIM_NONPRD_DBA;
GRANT OPERATE ON WAREHOUSE MIM_DEV_DATA_LOADER TO ROLE MIM_NONPRD_DBA;

GRANT USAGE ON WAREHOUSE MIM_PRD_DATA_LOADER TO ROLE MIM_PRD_DBA;
GRANT OPERATE ON WAREHOUSE MIM_PRD_DATA_LOADER TO ROLE MIM_PRD_DBA;

-- Continue similar grants for all MIM roles and warehouses
