-- Domains: RAD, ESG, MIM
-- Environments: DEV, TST, PRD

-- Create roles for RAD domain
CREATE ROLE RAD_NONPRD_DBA;
CREATE ROLE RAD_PRD_DBA;

CREATE ROLE RAD_DEV_ETL;
CREATE ROLE RAD_TST_ETL;
CREATE ROLE RAD_PRD_ETL;

CREATE ROLE RAD_DEV_RW;
CREATE ROLE RAD_TST_RW;
CREATE ROLE RAD_PRD_RW;

CREATE ROLE RAD_DEV_RO;
CREATE ROLE RAD_TST_RO;
CREATE ROLE RAD_PRD_RO;

-- Create roles for ESG domain
CREATE ROLE ESG_NONPRD_DBA;
CREATE ROLE ESG_PRD_DBA;

CREATE ROLE ESG_DEV_ETL;
CREATE ROLE ESG_TST_ETL;
CREATE ROLE ESG_PRD_ETL;

CREATE ROLE ESG_DEV_RW;
CREATE ROLE ESG_TST_RW;
CREATE ROLE ESG_PRD_RW;

CREATE ROLE ESG_DEV_RO;
CREATE ROLE ESG_TST_RO;
CREATE ROLE ESG_PRD_RO;

-- Create roles for MIM domain
CREATE ROLE MIM_NONPRD_DBA;
CREATE ROLE MIM_PRD_DBA;

CREATE ROLE MIM_DEV_ETL;
CREATE ROLE MIM_TST_ETL;
CREATE ROLE MIM_PRD_ETL;

CREATE ROLE MIM_DEV_RW;
CREATE ROLE MIM_TST_RW;
CREATE ROLE MIM_PRD_RW;

CREATE ROLE MIM_DEV_RO;
CREATE ROLE MIM_TST_RO;
CREATE ROLE MIM_PRD_RO;
